import type { Metadata } from "next";
import { Toaster } from "@/components/ui/sonner";
import { Inter, Roboto_Slab, Alegreya, Alegreya_Sans } from "next/font/google";
import "./globals.css";
import { TooltipProvider } from "@/components/ui/tooltip";
import { cn } from "@/lib/utils";

const alegreya = Alegreya({
  weight: "variable",
  subsets: ["latin"],
  variable: "--font-alegreya",
});
const alegreyaSans = Alegreya_Sans({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  variable: "--font-alegreya-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn(alegreya.variable, alegreyaSans.variable)}>
      <body>
        <TooltipProvider>{children}</TooltipProvider>
        <Toaster />
      </body>
    </html>
  );
}
