import { Character } from "@/supabase/schema";
import {
  DraftingCompass,
  Feather,
  Leaf,
  LucideIcon,
  MessageCircle,
  PersonStanding,
} from "lucide-react";
import * as optolith from "../optolith";
import { Attribute } from "./attributes";

export type SkillGroup = {
  id: "physical" | "social" | "nature" | "knowledge" | "craft";
  name: { en: string; de: string };
  Icon: LucideIcon;
  attributes: [Attribute["id"], Attribute["id"], Attribute["id"]];
};

export const skillGroups = [
  {
    id: "physical",
    name: { en: "Physical Skills", de: "Körpertalente" },
    Icon: PersonStanding,
    // MU/GE/KK
    attributes: [1, 6, 8],
  },
  {
    id: "social",
    name: { en: "Social Skills", de: "Gesellschaftstalente" },
    Icon: MessageCircle,
    // IN/CH/CH
    attributes: [3, 4, 4],
  },
  {
    id: "nature",
    name: { en: "Nature Skills", de: "Naturtalente" },
    Icon: Leaf,
    // MU/GE/KO
    attributes: [1, 6, 7],
  },
  {
    id: "knowledge",
    name: { en: "Knowledge Skills", de: "Wissenstalente" },
    Icon: Feather,
    // KL/KL/IN
    attributes: [2, 2, 3],
  },
  {
    id: "craft",
    name: { en: "Craft Skills", de: "Handwerkstalente" },
    Icon: DraftingCompass,
    // FF/FF/KO
    attributes: [5, 5, 7],
  },
] as const satisfies SkillGroup[];

export type IncreaseFactor = "A" | "B" | "C" | "D" | "E" | "F";

export type Skill = {
  id: number;
  optolithId: optolith.SkillId;
  name: { en: string; de: string };
  group: SkillGroup["id"];
  attributes: [Attribute["id"], Attribute["id"], Attribute["id"]];
  isEncumbranceApplicable: boolean | "maybe";
  increaseFactor: IncreaseFactor;
};

export const skills = [
  {
    id: 1,
    optolithId: optolith.SkillId.Flying,
    name: { en: "Flying", de: "Fliegen" },
    group: "physical",
    attributes: [1, 3, 6],
    isEncumbranceApplicable: true,
    increaseFactor: "B",
  },
  {
    id: 2,
    optolithId: optolith.SkillId.Gaukelei,
    name: { en: "Gaukelei", de: "Gaukelei" },
    group: "physical",
    attributes: [1, 4, 5],
    isEncumbranceApplicable: true,
    increaseFactor: "A",
  },
  {
    id: 3,
    optolithId: optolith.SkillId.Climbing,
    name: { en: "Climbing", de: "Klettern" },
    group: "physical",
    attributes: [1, 6, 8],
    isEncumbranceApplicable: true,
    increaseFactor: "B",
  },
  {
    id: 4,
    optolithId: optolith.SkillId.BodyControl,
    name: { en: "Body Control", de: "Körperbeherrschung" },
    group: "physical",
    attributes: [6, 6, 7],
    isEncumbranceApplicable: true,
    increaseFactor: "D",
  },
  {
    id: 5,
    optolithId: optolith.SkillId.FeatOfStrength,
    name: { en: "Feat of Strength", de: "Kraftakt" },
    group: "physical",
    attributes: [7, 8, 8],
    isEncumbranceApplicable: true,
    increaseFactor: "B",
  },
  {
    id: 6,
    optolithId: optolith.SkillId.Riding,
    name: { en: "Riding", de: "Reiten" },
    group: "physical",
    attributes: [4, 6, 8],
    isEncumbranceApplicable: true,
    increaseFactor: "B",
  },
  {
    id: 7,
    optolithId: optolith.SkillId.Swimming,
    name: { en: "Swimming", de: "Schwimmen" },
    group: "physical",
    attributes: [6, 7, 8],
    isEncumbranceApplicable: true,
    increaseFactor: "B",
  },
  {
    id: 8,
    optolithId: optolith.SkillId.SelfControl,
    name: { en: "Self-Control", de: "Selbstbeherrschung" },
    group: "physical",
    attributes: [1, 1, 7],
    isEncumbranceApplicable: false,
    increaseFactor: "D",
  },
  {
    id: 9,
    optolithId: optolith.SkillId.Singing,
    name: { en: "Singing", de: "Singen" },
    group: "physical",
    attributes: [2, 4, 7],
    isEncumbranceApplicable: "maybe",
    increaseFactor: "A",
  },
  {
    id: 10,
    optolithId: optolith.SkillId.Perception,
    name: { en: "Perception", de: "Sinnesschärfe" },
    group: "physical",
    attributes: [2, 3, 3],
    isEncumbranceApplicable: "maybe",
    increaseFactor: "D",
  },
  {
    id: 11,
    optolithId: optolith.SkillId.Dancing,
    name: { en: "Dancing", de: "Tanzen" },
    group: "physical",
    attributes: [2, 4, 6],
    isEncumbranceApplicable: true,
    increaseFactor: "A",
  },
  {
    id: 12,
    optolithId: optolith.SkillId.Pickpocket,
    name: { en: "Pickpocket", de: "Taschendiebstahl" },
    group: "physical",
    attributes: [1, 5, 6],
    isEncumbranceApplicable: true,
    increaseFactor: "B",
  },
  {
    id: 13,
    optolithId: optolith.SkillId.Stealth,
    name: { en: "Stealth", de: "Verbergen" },
    group: "physical",
    attributes: [1, 3, 6],
    isEncumbranceApplicable: true,
    increaseFactor: "C",
  },
  {
    id: 14,
    optolithId: optolith.SkillId.Carousing,
    name: { en: "Carousing", de: "Zechen" },
    group: "physical",
    attributes: [1, 7, 8],
    isEncumbranceApplicable: false,
    increaseFactor: "A",
  },
  {
    id: 15,
    optolithId: optolith.SkillId.Persuasion,
    name: { en: "Persuasion", de: "Bekehren & Überzeugen" },
    group: "social",
    attributes: [1, 2, 4],
    isEncumbranceApplicable: false,
    increaseFactor: "B",
  },
  {
    id: 16,
    optolithId: optolith.SkillId.Seduction,
    name: { en: "Seduction", de: "Betören" },
    group: "social",
    attributes: [1, 4, 4],
    isEncumbranceApplicable: "maybe",
    increaseFactor: "B",
  },
  {
    id: 17,
    optolithId: optolith.SkillId.Intimidation,
    name: { en: "Intimidation", de: "Einschüchtern" },
    group: "social",
    attributes: [1, 3, 4],
    isEncumbranceApplicable: false,
    increaseFactor: "B",
  },
  {
    id: 18,
    optolithId: optolith.SkillId.Etiquette,
    name: { en: "Etiquette", de: "Etikette" },
    group: "social",
    attributes: [2, 3, 4],
    isEncumbranceApplicable: false,
    increaseFactor: "B",
  },
  {
    id: 19,
    optolithId: optolith.SkillId.Streetwise,
    name: { en: "Streetwise", de: "Gassenwissen" },
    group: "social",
    attributes: [2, 3, 4],
    isEncumbranceApplicable: "maybe",
    increaseFactor: "C",
  },
  {
    id: 20,
    optolithId: optolith.SkillId.Empathy,
    name: { en: "Empathy", de: "Menschenkenntnis" },
    group: "social",
    attributes: [2, 3, 4],
    isEncumbranceApplicable: false,
    increaseFactor: "C",
  },
  {
    id: 21,
    optolithId: optolith.SkillId.FastTalk,
    name: { en: "Fast Talk", de: "Überreden" },
    group: "social",
    attributes: [1, 3, 4],
    isEncumbranceApplicable: false,
    increaseFactor: "C",
  },
  {
    id: 22,
    optolithId: optolith.SkillId.Disguise,
    name: { en: "Disguise", de: "Verkleiden" },
    group: "social",
    attributes: [3, 4, 6],
    isEncumbranceApplicable: false,
    increaseFactor: "B",
  },
  {
    id: 23,
    optolithId: optolith.SkillId.Willpower,
    name: { en: "Willpower", de: "Willenskraft" },
    group: "social",
    attributes: [1, 3, 4],
    isEncumbranceApplicable: false,
    increaseFactor: "D",
  },
  {
    id: 24,
    optolithId: optolith.SkillId.Tracking,
    name: { en: "Tracking", de: "Fährtensuchen" },
    group: "nature",
    attributes: [1, 3, 4],
    isEncumbranceApplicable: true,
    increaseFactor: "C",
  },
  {
    id: 25,
    optolithId: optolith.SkillId.Ropes,
    name: { en: "Ropes", de: "Fesseln" },
    group: "nature",
    attributes: [2, 5, 8],
    isEncumbranceApplicable: "maybe",
    increaseFactor: "A",
  },
  {
    id: 26,
    optolithId: optolith.SkillId.Fishing,
    name: { en: "Fishing", de: "Fischen & Angeln" },
    group: "nature",
    attributes: [5, 6, 7],
    isEncumbranceApplicable: "maybe",
    increaseFactor: "A",
  },
  {
    id: 27,
    optolithId: optolith.SkillId.Orienting,
    name: { en: "Orienting", de: "Orientierung" },
    group: "nature",
    attributes: [2, 3, 3],
    isEncumbranceApplicable: false,
    increaseFactor: "B",
  },
  {
    id: 28,
    optolithId: optolith.SkillId.PlantLore,
    name: { en: "Plant Lore", de: "Pflanzenkunde" },
    group: "nature",
    attributes: [2, 5, 7],
    isEncumbranceApplicable: "maybe",
    increaseFactor: "C",
  },
  {
    id: 29,
    optolithId: optolith.SkillId.AnimalLore,
    name: { en: "Animal Lore", de: "Tierkunde" },
    group: "nature",
    attributes: [1, 1, 4],
    isEncumbranceApplicable: true,
    increaseFactor: "C",
  },
  {
    id: 30,
    optolithId: optolith.SkillId.Survival,
    name: { en: "Survival", de: "Wildnisleben" },
    group: "nature",
    attributes: [1, 6, 7],
    isEncumbranceApplicable: true,
    increaseFactor: "C",
  },
  {
    id: 31,
    optolithId: optolith.SkillId.Gambling,
    name: { en: "Gambling", de: "Brett- & Glücksspiel" },
    group: "knowledge",
    attributes: [2, 2, 3],
    isEncumbranceApplicable: false,
    increaseFactor: "A",
  },
  {
    id: 32,
    optolithId: optolith.SkillId.Geography,
    name: { en: "Geography", de: "Geographie" },
    group: "knowledge",
    attributes: [2, 2, 3],
    isEncumbranceApplicable: false,
    increaseFactor: "B",
  },
  {
    id: 33,
    optolithId: optolith.SkillId.History,
    name: { en: "History", de: "Geschichtswissen" },
    group: "knowledge",
    attributes: [2, 2, 3],
    isEncumbranceApplicable: false,
    increaseFactor: "B",
  },
  {
    id: 34,
    optolithId: optolith.SkillId.Religions,
    name: { en: "Religions", de: "Götter & Kulte" },
    group: "knowledge",
    attributes: [2, 2, 3],
    isEncumbranceApplicable: false,
    increaseFactor: "B",
  },

  {
    id: 35,
    optolithId: optolith.SkillId.Warfare,
    name: { en: "Warfare", de: "Kriegskunst" },
    group: "knowledge",
    attributes: [1, 2, 3],
    isEncumbranceApplicable: false,
    increaseFactor: "B",
  },
  {
    id: 36,
    optolithId: optolith.SkillId.MagicalLore,
    name: { en: "Magical Lore", de: "Magiekunde" },
    group: "knowledge",
    attributes: [2, 2, 3],
    isEncumbranceApplicable: false,
    increaseFactor: "C",
  },
  {
    id: 37,
    optolithId: optolith.SkillId.Mechanics,
    name: { en: "Mechanics", de: "Mechanik" },
    group: "knowledge",
    attributes: [2, 2, 5],
    isEncumbranceApplicable: false,
    increaseFactor: "B",
  },
  {
    id: 38,
    optolithId: optolith.SkillId.Math,
    name: { en: "Math", de: "Rechnen" },
    group: "knowledge",
    attributes: [2, 2, 3],
    isEncumbranceApplicable: false,
    increaseFactor: "A",
  },
  {
    id: 39,
    optolithId: optolith.SkillId.Law,
    name: { en: "Law", de: "Rechtskunde" },
    group: "knowledge",
    attributes: [2, 2, 3],
    isEncumbranceApplicable: false,
    increaseFactor: "A",
  },
  {
    id: 40,
    optolithId: optolith.SkillId.MythsAndLegends,
    name: { en: "Myths and Legends", de: "Sagen & Legenden" },
    group: "knowledge",
    attributes: [2, 2, 3],
    isEncumbranceApplicable: false,
    increaseFactor: "B",
  },
  {
    id: 41,
    optolithId: optolith.SkillId.SphereLore,
    name: { en: "Sphere Lore", de: "Sphärenkunde" },
    group: "knowledge",
    attributes: [2, 2, 3],
    isEncumbranceApplicable: false,
    increaseFactor: "B",
  },
  {
    id: 42,
    optolithId: optolith.SkillId.Astronomy,
    name: { en: "Astronomy", de: "Sternkunde" },
    group: "knowledge",
    attributes: [2, 2, 3],
    isEncumbranceApplicable: false,
    increaseFactor: "A",
  },
  {
    id: 43,
    optolithId: optolith.SkillId.Alchemy,
    name: { en: "Alchemy", de: "Alchemie" },
    group: "craft",
    attributes: [1, 2, 5],
    isEncumbranceApplicable: true,
    increaseFactor: "C",
  },
  {
    id: 44,
    optolithId: optolith.SkillId.Sailing,
    name: { en: "Sailing", de: "Boote & Schiffe" },
    group: "craft",
    attributes: [5, 6, 8],
    isEncumbranceApplicable: true,
    increaseFactor: "B",
  },
  {
    id: 45,
    optolithId: optolith.SkillId.Driving,
    name: { en: "Driving", de: "Fahrzeuge" },
    group: "craft",
    attributes: [4, 5, 7],
    isEncumbranceApplicable: true,
    increaseFactor: "A",
  },
  {
    id: 46,
    optolithId: optolith.SkillId.Commerce,
    name: { en: "Commerce", de: "Handel" },
    group: "craft",
    attributes: [2, 3, 4],
    isEncumbranceApplicable: false,
    increaseFactor: "B",
  },
  {
    id: 47,
    optolithId: optolith.SkillId.TreatPoison,
    name: { en: "Treat Poison", de: "Heilkunde Gift" },
    group: "craft",
    attributes: [1, 2, 3],
    isEncumbranceApplicable: true,
    increaseFactor: "B",
  },
  {
    id: 48,
    optolithId: optolith.SkillId.TreatDisease,
    name: { en: "Treat Disease", de: "Heilkunde Krankheiten" },
    group: "craft",
    attributes: [1, 3, 7],
    isEncumbranceApplicable: true,
    increaseFactor: "B",
  },
  {
    id: 49,
    optolithId: optolith.SkillId.TreatSoul,
    name: { en: "Treat Soul", de: "Heilkunde Seele" },
    group: "craft",
    attributes: [1, 4, 7],
    isEncumbranceApplicable: false,
    increaseFactor: "B",
  },
  {
    id: 50,
    optolithId: optolith.SkillId.TreatWounds,
    name: { en: "Treat Wounds", de: "Heilkunde Wunden" },
    group: "craft",
    attributes: [2, 5, 5],
    isEncumbranceApplicable: true,
    increaseFactor: "D",
  },
  {
    id: 51,
    optolithId: optolith.SkillId.Woodworking,
    name: { en: "Woodworking", de: "Holzbearbeitung" },
    group: "craft",
    attributes: [5, 6, 8],
    isEncumbranceApplicable: true,
    increaseFactor: "B",
  },
  {
    id: 52,
    optolithId: optolith.SkillId.PrepareFood,
    name: { en: "Prepare Food", de: "Lebensmittelbearbeitung" },
    group: "craft",
    attributes: [3, 5, 5],
    isEncumbranceApplicable: true,
    increaseFactor: "A",
  },
  {
    id: 53,
    optolithId: optolith.SkillId.Leatherworking,
    name: { en: "Leatherworking", de: "Lederbearbeitung" },
    group: "craft",
    attributes: [5, 6, 7],
    isEncumbranceApplicable: true,
    increaseFactor: "B",
  },
  {
    id: 54,
    optolithId: optolith.SkillId.ArtisticAbility,
    name: { en: "Artistic Ability", de: "Malen & Zeichnen" },
    group: "craft",
    attributes: [3, 5, 5],
    isEncumbranceApplicable: true,
    increaseFactor: "A",
  },
  {
    id: 55,
    optolithId: optolith.SkillId.Metalworking,
    name: { en: "Metalworking", de: "Metallbearbeitung" },
    group: "craft",
    attributes: [5, 7, 8],
    isEncumbranceApplicable: true,
    increaseFactor: "C",
  },
  {
    id: 56,
    optolithId: optolith.SkillId.Music,
    name: { en: "Music", de: "Musizieren" },
    group: "craft",
    attributes: [4, 5, 7],
    isEncumbranceApplicable: true,
    increaseFactor: "A",
  },
  {
    id: 57,
    optolithId: optolith.SkillId.PickLocks,
    name: { en: "Pick Locks", de: "Schlösserknacken" },
    group: "craft",
    attributes: [3, 5, 5],
    isEncumbranceApplicable: true,
    increaseFactor: "C",
  },
  {
    id: 58,
    optolithId: optolith.SkillId.Earthencraft,
    name: { en: "Earthencraft", de: "Steinbearbeitung" },
    group: "craft",
    attributes: [5, 5, 8],
    isEncumbranceApplicable: true,
    increaseFactor: "A",
  },
  {
    id: 59,
    optolithId: optolith.SkillId.Clothworking,
    name: { en: "Clothworking", de: "Stoffbearbeitung" },
    group: "craft",
    attributes: [2, 5, 5],
    isEncumbranceApplicable: true,
    increaseFactor: "A",
  },
] as const satisfies Skill[];

export function getSkillPoints(skillId: number, character: Character) {
  return (
    character.data.talents[
      skills.find(({ id }) => id === skillId)!.optolithId
    ] ?? 0
  );
}
